export const playerStatsGridColumns = [
  { fieldName: 'Name', sortable: true, width: 180 },
  { fieldName: 'TeamAbbre', sortable: true, centered: true, headerTitle: 'Team' },
  { fieldName: 'Position', sortable: true, centered: true, headerTitle: 'Pos', title: 'Position' },
  { fieldName: 'GP', sortable: true, centered: true },
  { fieldName: 'G', sortable: true, centered: true },
  { fieldName: 'A', sortable: true, centered: true },
  { fieldName: 'P', sortable: true, centered: true},
  { fieldName: 'PlusMinus', sortable: true, centered: true, headerTitle: '+/-' },
  { fieldName: 'Pim', sortable: true, centered: true },
  { fieldName: 'Hits', sortable: true, centered: true },
  { fieldName: 'Shots', sortable: true, centered: true },
  { fieldName: 'ShotsPCT', sortable: true, centered: true, headerTitle: 'Shot%',
    template: `<span ng-bind="row.ShotsPCT | number : 1"></span>` },
  { fieldName: 'ShotsBlock', sortable: true, centered: true, headerTitle: 'BkS' },
  { fieldName: 'AvgTOI', sortable: true, centered: true, headerTitle: 'TOI/G',
    template: '<span ng-bind="row.AvgTOI | time"></span>' },
  { fieldName: 'PPG', sortable: true, centered: true },
  { fieldName: 'PPA', sortable: true, centered: true },
  { fieldName: 'PPP', sortable: true, centered: true },
  { fieldName: 'P60', sortable: true, centered: true, headerTitle: 'P/60',
    template: `<span ng-bind="row.P60 || 0 | number : 1"></span>` }
];
