export const skaterRatingsGridColumns = [
  { fieldName: 'Name', sortable: true, width: 180 },
  { fieldName: 'TeamAbbre', sortable: true, centered: true, headerTitle: 'Team' },
  { fieldName: 'Position', sortable: true, centered: true, headerTitle: 'Pos', title: 'Position' },
  { fieldName: 'Condition', sortable: true, centered: true, headerTitle: 'Con', title: 'Condition' },
  { fieldName: 'CK', sortable: true, centered: true, title: 'Checking' },
  { fieldName: 'FG', sortable: true, centered: true, title: 'Fighting' },
  { fieldName: 'DI', sortable: true, centered: true, title: 'Discipline' },
  { fieldName: 'SK', sortable: true, centered: true, title: 'Skating' },
  { fieldName: 'ST', sortable: true, centered: true, title: 'Strength' },
  { fieldName: 'EN', sortable: true, centered: true, title: 'Endurance' },
  { fieldName: 'DU', sortable: true, centered: true, title: 'Durability' },
  { fieldName: 'PH', sortable: true, centered: true, title: 'Puck Handling' },
  { fieldName: 'FO', sortable: true, centered: true, title: 'Faceoffs' },
  { fieldName: 'PA', sortable: true, centered: true, title: 'Passing' },
  { fieldName: 'SC', sortable: true, centered: true, title: 'Scoring' },
  { fieldName: 'DF', sortable: true, centered: true, title: 'Defense' },
  { fieldName: 'PS', sortable: true, centered: true, title: 'Penalty Shot' },
  { fieldName: 'EX', sortable: true, centered: true, title: 'Experience' },
  { fieldName: 'LD', sortable: true, centered: true, title: 'Leadership' },
  { fieldName: 'PO', sortable: true, centered: true, title: 'Potential' },
  { fieldName: 'MO', sortable: true, centered: true, title: 'Morale' },
  { fieldName: 'Overall', sortable: true, centered: true, headerTitle: 'OV', title: 'Overall' },
  { fieldName: 'AvailableforTrade', sortable: true, centered: true, headerTitle: 'TA',
    title: 'Available for Trade',
    template: `<span>{{ row.AvailableForTrade === 'True' ? '&#10004' : '' }}</span>` },
  { fieldName: 'StarPower', sortable: true, centered: true, headerTitle: 'SP', title: 'Star Power' }
];
