export const goalieStatsGridColumns = [
  { fieldName: 'Name', sortable: true, width: 180 },
  { fieldName: 'TeamAbbre', sortable: true, centered: true, headerTitle: 'Team' },
  { fieldName: 'GP', sortable: true, centered: true, title: 'Games Played' },
  { fieldName: 'W', sortable: true, centered: true, title: 'Wins' },
  { fieldName: 'L', sortable: true, centered: true, title: 'Losses' },
  { fieldName: 'OTL', sortable: true, centered: true, title: 'Overtime Losses' },
  { fieldName: 'PCT', sortable: true, centered: true, headerTitle: 'SV%', title: 'Save Percentage',
    template: '<span ng-bind="row.PCT | number: 3"></span>' },
  { fieldName: 'GAA', sortable: true, centered: true, title: 'Goals-Against Average',
    template: '<span ng-bind="row.GAA | number: 3"></span>' },
  { fieldName: 'SecondPlay', sortable: true, centered: true, headerTitle: 'MIN', title: 'Minutes Played',
    template: `<span ng-bind="row.SecondPlay | time"></span>` },
  { fieldName: 'Pim', sortable: true, centered: true, title: 'Penalty Minutes' },
  // For some reason Shootout = Shutout in the DB
  { fieldName: 'Shootout', sortable: true, centered: true, headerTitle: 'SO', title: 'Shutouts' },
  { fieldName: 'GA', sortable: true, centered: true, title: 'Goals Against' },
  { fieldName: 'SA', sortable: true, centered: true, title: 'Shots Against' },
  { fieldName: 'A', sortable: true, centered: true, title: 'Assists' },
  { fieldName: 'EmptyNetGoal', sortable: true, centered: true, headerTitle: 'EN', title: 'Empty-Net Goals Against' },
  { fieldName: 'PenaltyShotsPCT', sortable: true, centered: true, headerTitle: 'PS%',
    title: 'Penalty Shot Save Percentage',
    template: '<span ng-bind="row.PenaltyShotsPCT | number: 3"></span>' },
  { fieldName: 'PenalityShotsShots', sortable: true, centered: true, headerTitle: 'PSA',
    title: 'Penalty Shots Against' }
];
