export const goalieRatingsGridColumns = [
  { fieldName: 'Name', sortable: true, width: 180 },
  { fieldName: 'TeamAbbre', sortable: true, centered: true, headerTitle: 'Team' },
  { fieldName: 'Condition', sortable: true, centered: true, headerTitle: 'Con', title: 'Conditioning' },
  { fieldName: 'SK', sortable: true, centered: true, title: 'Skating' },
  { fieldName: 'DU', sortable: true, centered: true, title: 'Durability' },
  { fieldName: 'EN', sortable: true, centered: true, title: 'Endurance' },
  { fieldName: 'SZ', sortable: true, centered: true, title: 'Size' },
  { fieldName: 'AG', sortable: true, centered: true, title: 'Agility' },
  { fieldName: 'RB', sortable: true, centered: true, title: 'Rebound Control' },
  { fieldName: 'SC', sortable: true, centered: true, title: 'Style Control' },
  { fieldName: 'HS', sortable: true, centered: true, title: 'Hand Speed' },
  { fieldName: 'RT', sortable: true, centered: true, title: 'Reaction Time' },
  { fieldName: 'PH', sortable: true, centered: true, title: 'Puck Handling' },
  { fieldName: 'PS', sortable: true, centered: true, title: 'Penalty Shot' },
  { fieldName: 'EX', sortable: true, centered: true, title: 'Experience' },
  { fieldName: 'LD', sortable: true, centered: true, title: 'Leadership' },
  { fieldName: 'PO', sortable: true, centered: true, title: 'Potential' },
  { fieldName: 'MO', sortable: true, centered: true, title: 'Morale' },
  { fieldName: 'Overall', sortable: true, centered: true, headerTitle: 'OV', title: 'Overall' },
  { fieldName: 'AvailableforTrade', sortable: true, centered: true, headerTitle: 'TA', title: 'Trade Available',
    template: `<span>{{ row.AvailableForTrade === 'True' ? '&#10004' : '' }}</span>` },
  { fieldName: 'StarPower', sortable: true, centered: true, headerTitle: 'SP', title: 'Star Power' }
];
